services:
  backend:
    build: ./backend
    networks:
      - internal
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - internal
    depends_on:
      - backend
    restart: unless-stopped

networks:
  internal:
    driver: bridge